openapi: 3.0.0
info:
  title: uptime-kuma
  version: 1.0.0
servers:
  - url: http://localhost:3001
paths:
  /info:
    post:
      tags:
        - default
      summary: uptime-kuma
      responses:
        "200":
          description: Successful response
          content:
            application/json: { }
